version: "3.7"
services:
  app:
    build:
      args:
        user: angelo
        uid: 1000
      context: ./
      dockerfile: ./docker/php/Dockerfile
    image: app-php
    container_name: app
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app-php-network

  db:
    image: mysql:5.7
    container_name: db
    ports: ["3326:3306"]
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - app-php-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - app-php-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6380:6379
    volumes:
      - redis-data:/data
    networks:
      - app-php-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - app-php-network
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 1G
    depends_on:
      - db
    ports:
      - 8081:80
    volumes:
      - /sessions

volumes:
  db-volume: {}

networks:
  app-php-network:
    driver: bridge
    name: app-php-network
